// <auto-generated />
using DbModel.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DbModel.Migrations
{
    [DbContext(typeof(FoodContext))]
    partial class FoodContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DbModel.Model.FoodBrand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("FoodBrands");
                });

            modelBuilder.Entity("DbModel.Model.FoodProduct", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FoodBrandId")
                        .HasColumnType("int");

                    b.Property<int>("FoodType")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FoodBrandId");

                    b.ToTable("FoodProducts");
                });

            modelBuilder.Entity("DbModel.Model.Storage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Storages");
                });

            modelBuilder.Entity("DbModel.Models.FoodMixture", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("FoodMixtures");
                });

            modelBuilder.Entity("DbModel.Models.FoodMixtureItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("FoodMixtureId")
                        .HasColumnType("int");

                    b.Property<int>("FoodProductItemId")
                        .HasColumnType("int");

                    b.Property<int>("ItemWeightInGram")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FoodMixtureId");

                    b.HasIndex("FoodProductItemId");

                    b.ToTable("FoodMixtureItems");
                });

            modelBuilder.Entity("DbModel.Models.FoodProductItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ContainerType")
                        .HasColumnType("int");

                    b.Property<int>("FoodProductId")
                        .HasColumnType("int");

                    b.Property<int>("WeightInGram")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FoodProductId");

                    b.ToTable("FoodProductItems");
                });

            modelBuilder.Entity("DbModel.Models.StorageItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("FoodMixtureId")
                        .HasColumnType("int");

                    b.Property<int?>("FoodProductItemId")
                        .HasColumnType("int");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(4, 4)
                        .HasColumnType("decimal(4,4)");

                    b.Property<int>("StorageId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FoodMixtureId");

                    b.HasIndex("FoodProductItemId");

                    b.HasIndex("StorageId");

                    b.ToTable("StorageItems");
                });

            modelBuilder.Entity("DbModel.Model.FoodProduct", b =>
                {
                    b.HasOne("DbModel.Model.FoodBrand", "FoodBrand")
                        .WithMany("Products")
                        .HasForeignKey("FoodBrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FoodBrand");
                });

            modelBuilder.Entity("DbModel.Models.FoodMixtureItem", b =>
                {
                    b.HasOne("DbModel.Models.FoodMixture", "FoodMixture")
                        .WithMany("Items")
                        .HasForeignKey("FoodMixtureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DbModel.Models.FoodProductItem", "FoodProductItem")
                        .WithMany()
                        .HasForeignKey("FoodProductItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FoodMixture");

                    b.Navigation("FoodProductItem");
                });

            modelBuilder.Entity("DbModel.Models.FoodProductItem", b =>
                {
                    b.HasOne("DbModel.Model.FoodProduct", "FoodProduct")
                        .WithMany("Items")
                        .HasForeignKey("FoodProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FoodProduct");
                });

            modelBuilder.Entity("DbModel.Models.StorageItem", b =>
                {
                    b.HasOne("DbModel.Models.FoodMixture", "FoodMixture")
                        .WithMany()
                        .HasForeignKey("FoodMixtureId");

                    b.HasOne("DbModel.Models.FoodProductItem", "FoodProductItem")
                        .WithMany()
                        .HasForeignKey("FoodProductItemId");

                    b.HasOne("DbModel.Model.Storage", "Storage")
                        .WithMany("Items")
                        .HasForeignKey("StorageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FoodMixture");

                    b.Navigation("FoodProductItem");

                    b.Navigation("Storage");
                });

            modelBuilder.Entity("DbModel.Model.FoodBrand", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("DbModel.Model.FoodProduct", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("DbModel.Model.Storage", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("DbModel.Models.FoodMixture", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
